language: node_js
node_js:
  - '0.10'
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || false'
env:
  global:
  - secure: L36j3mbU1U2FiOhxYZrTZ7apVnb56gE+QFixsYyDpCRBrVW0q8WR9LTMJx+aPNdlzhRS5FT4gfInujPTnZeb+EvqEoYwtT+CeNG15XtGkfJDkfBFjBa4IZpJAjIwJB+0kKkZr9R7lQEEgy7H9FvLHY2N2WgdzuG8WZwiVRnkwVw=
  - secure: K6NxT5qIzV/4Ce1HqoYMdpFtqxx5S5Ua/sKp1bbHCXTCft6gLBR3mrf1RR14Wj9AwcM9QY6YbNF/dXGmBdMNtiJN+a2nvcfIoPTGJ3UpK4r2xI5w/U+uhRQMxD55SkWaxUIPvEfgvwyETSpFZRYACnNkpxeQWMkdc14vk74Feu0=
matrix:
  include:
  - node_js: '0.10'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=firefox BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=safari BROWSER_VERSION=5
  - node_js: '0.10'
    env: BROWSER_NAME=safari BROWSER_VERSION=6
  - node_js: '0.10'
    env: BROWSER_NAME=safari BROWSER_VERSION=7
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=6
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=7
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=8
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=9
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=10 BROWSER_PLATFORM="Windows 2012"
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=latest BROWSER_PLATFORM="Windows 2012"
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=5.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=6.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=8.0
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.0
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.1
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.2
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.3
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.4