ui: mocha-bdd
scripts:
  - "/config.js"
  - "/domain.js"
server: ./tests/support/sockjs_server.js
tunnel:
  type: ngrok
  proto: tcp
capabilities:
  record-video: false
  record-screenshots: false
  avoid-proxy: true
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 6..latest
  - name: iphone
    version: 8.1..latest
  - name: android
    version: 4.1..latest
