ui: mocha-bdd
scripts:
  - "domain.js"
server: ./tests/support/sockjs_server.js
tunnel_provider: ngrok
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 6..latest
  - name: iphone
    version: 5.1..latest
  - name: android
    version: 4.0..latest